# Generated by Django 4.1.7 on 2023-03-09 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.PositiveIntegerField(default=0)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('alias', models.CharField(max_length=60, verbose_name='Alias')),
                ('pizarra', models.CharField(default='-', max_length=8, verbose_name='Pizarra')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/%d', verbose_name='Logo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('codigo', models.PositiveIntegerField(verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('codigo', models.PositiveIntegerField(verbose_name='Código')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Descripción')),
                ('extension', models.CharField(max_length=5, verbose_name='Extensión')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('middle_name', models.CharField(max_length=60, verbose_name='Primer Apellido')),
                ('last_name', models.CharField(max_length=60, verbose_name='Segundo Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=8, verbose_name='Teléfono fijo')),
                ('mobile', models.CharField(max_length=8, verbose_name='Celular')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('date_desactivate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de eliminación')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Extensión',
                'verbose_name_plural': 'Extensiones',
                'db_table': 'extensiones',
                'ordering': ['extension'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=11, unique=True, verbose_name='Dni')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('date_creation', models.DateTimeField(auto_now=True, verbose_name='Fecha de creación')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización')),
                ('age', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
                ('categ', models.ManyToManyField(to='core.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
    ]
